#!/usr/bin/env python3
"""
produce_lectures.py — Antigravity (agy) CLI orchestrator for react-lecture-03.

Runs one fresh agy (Gemini) CLI session per lecture. Each session makes the agent
write the prelecture (md-pre-lectures/{nn}.md), the production lecture
(md-lectures/{nn}.md) with its HTML figure files, then build the project with
`node src/build-lectures.mjs` until the build is clean, so the per-lecture PDF
(md-lectures-pdf/{nn}.pdf) and the combined course-reader deck are produced.

Only after the current question's PDF is verified fresh on disk does the script
launch the next iteration with a brand-new agy process. Any failure (model not
available, agy exits non-zero, missing or stale PDF/deck) stops the whole run.

Usage:
    python3 produce_lectures.py 3                     # next 3 questions, auto-detect start
    python3 produce_lectures.py --start 40 --chapters 1
    python3 produce_lectures.py --dry-run             # show plan + prompt, invoke nothing
    python3 produce_lectures.py --model gemini-3.1-pro-high --chapters 2
"""

import argparse
import glob
import os
import re
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

# ----------------------------------------------------------------------------- paths

PROJECT = Path(__file__).resolve().parent
QUESTIONS_MD = PROJECT / "questions" / "questions.md"
PRE_DIR = PROJECT / "md-pre-lectures"
LEC_DIR = PROJECT / "md-lectures"
PDF_DIR = PROJECT / "md-lectures-pdf"
FIG_DIR = LEC_DIR / "figures"
LOG_DIR = PROJECT / "agy-logs"

DECK_GLOB = "React 19*.pdf"        # combined course-reader PDFs regenerated by the build
MAX_QUESTION = 180                 # size of the question bank
DEFAULT_AGY = "agy"                 # Antigravity CLI on PATH (v1.2.5: /Users/techton/.local/bin/agy)
DEFAULT_MODEL = "gemini-3.1-pro-high"
DEFAULT_TIMEOUT_MIN = 120          # per-iteration agy --print-timeout

# Verification floors: catch stub files the agent may leave behind.
MIN_PRE_BYTES = 200
MIN_LEC_BYTES = 1000
MIN_PDF_BYTES = 20000


def bn(n):
    """Lecture file basename: zero-padded for 1-99, natural for 100+ (01.md, 100.md)."""
    return f"{n:02d}"


# ----------------------------------------------------------------------------- question bank

def detect_next_question():
    """Next question = highest existing lecture number in md-lectures/ plus one."""
    if not LEC_DIR.is_dir():
        return 1
    numbers = [int(m.group(1)) for f in os.listdir(LEC_DIR)
               if (m := re.match(r"^(\d+)\.md$", f))]
    return max(numbers, default=0) + 1


def parse_question_row(n):
    """Pull the row `| n | tier | topic | question | hook |` from questions.md."""
    if not QUESTIONS_MD.is_file():
        sys.exit(f"FATAL: question bank not found: {QUESTIONS_MD}")
    text = QUESTIONS_MD.read_text(encoding="utf-8")
    for line in text.splitlines():
        if not re.match(rf"^\|\s*{n}\s*\|", line):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) >= 5:
            return {"tier": cells[1], "topic": cells[2],
                    "question": cells[3], "hook": cells[4]}
    return None


# ----------------------------------------------------------------------------- prompt

def build_prompt(n, row):
    prev = [f"md-lectures/{bn(p)}.md" for p in (n - 1, n - 2)
            if p >= 1 and (LEC_DIR / f"{bn(p)}.md").is_file()]
    prev_ref = ("the previous lecture(s) " + " and ".join(prev) +
                " for voice, world, and continuity") if prev else \
               "no earlier lectures exist yet, so this is the opening lecture of the course"

    return f"""ppp — proceed immediately, execute everything, ask no confirmation questions.

You are the production agent for the react-lecture-03 course (React 19 interview lectures, 180-question bank, The National Times world). Your task in this session is exactly one question, Q{n}, taken end to end. Do not start, sketch, or touch any other question.

The question row, verbatim from questions/questions.md:
- Number: {n}
- Tier: {row['tier']}
- Topic tag: {row['topic']}
- Question (copy verbatim into the lecture callout): {row['question']}
- Hook (the seed of the opening scenario; grow it, never replace it): {row['hook']}

Read first, before writing anything:
- questions/questions.md (your row and the rows around it)
- questions/topics.md
- PRE-LECTURE-INSTRUCTIONS.md (Phase 1 law)
- AUTHOR-BRIEF.md (Phase 2 skeleton and hard format rules)
- instructions.md (full project law; the Opening Ladder and summary sections especially)
- {prev_ref}

Deliverables, in this exact order:
1. Phase 1 prelecture: md-pre-lectures/{bn(n)}.md, following PRE-LECTURE-INSTRUCTIONS.md exactly.
2. Phase 2 production lecture: md-lectures/{bn(n)}.md, following AUTHOR-BRIEF.md exactly. That includes the mandatory components explorer panel, the mandatory html-figure fence, and its figure file(s) under md-lectures/figures/ cloned from the closest proven archetype in md-lectures/figures/templates/ and obeying docs/figure-design-system.md.
3. Build: run `node src/build-lectures.mjs` from the project root. Read the build output; fix every warn by editing your own files and rebuild. A clean build with zero warnings is the mechanical definition of done. The same build regenerates the combined course-reader deck.
4. Stop after confirming all three exist: md-pre-lectures/{bn(n)}.md, md-lectures/{bn(n)}.md, md-lectures-pdf/{bn(n)}.pdf.

Hard rules: one continuous line per paragraph (never hard-wrap), zero em-dashes, no screenshots or pdftoppm scans (text and build output only), and never modify any lecture, prelecture, figure, question row, or build script other than Q{n}'s own deliverables."""


# ----------------------------------------------------------------------------- agy runner

def preflight_model(agy, model):
    """Check the agy CLI is alive and the model is listed. Returns an error string or None."""
    try:
        proc = subprocess.run([agy, "models"], capture_output=True, text=True, timeout=120)
    except FileNotFoundError:
        return f"agy CLI not found at '{agy}' (is it installed and on PATH?)"
    except subprocess.TimeoutExpired:
        return "`agy models` preflight timed out after 120s"
    if proc.returncode != 0:
        return f"`agy models` exited {proc.returncode}: {proc.stderr.strip()[:300]}"
    if model not in (proc.stdout or ""):
        return f"model '{model}' is not available to the CLI right now. Run `agy models` to see the current list."
    return None


def run_agy(agy, model, effort, timeout_min, skip_permissions, prompt, log_path, t0):
    """One fresh agy process for one iteration. Streams output to console + log. Returns exit code."""
    cmd = [agy, "--prompt", prompt, "--model", model]
    if effort:
        cmd += ["--effort", effort]
    if skip_permissions:
        cmd += ["--dangerously-skip-permissions"]
    cmd += ["--print-timeout", f"{timeout_min}m"]

    with open(log_path, "w", encoding="utf-8") as log:
        log.write(f"# agy run | start {datetime.now().isoformat()}\n")
        log.write(f"# model: {model} | timeout: {timeout_min}m | cwd: {PROJECT}\n")
        log.write(f"# command flags: {cmd[:1]} <prompt {len(prompt)} chars> "
                  + " ".join(cmd[2:]) + "\n\n")
        log.write("=== PROMPT ===\n" + prompt + "\n\n=== OUTPUT ===\n")
        log.flush()

        print(f"    launching fresh agy session (model {model}, timeout {timeout_min}m)...",
              flush=True)
        proc = subprocess.Popen(cmd, cwd=str(PROJECT), stdout=subprocess.PIPE,
                                stderr=subprocess.STDOUT, text=True, bufsize=1)
        watchdog = timeout_min * 60 + 600   # CLI kills itself at --print-timeout; this is the backstop
        try:
            for line in proc.stdout:
                log.write(line)
                log.flush()
                print("    | " + line.rstrip())
            proc.wait(timeout=watchdog)
        except KeyboardInterrupt:
            print("\n    interrupted by user — terminating agy process", flush=True)
            proc.terminate()
            try:
                proc.wait(timeout=15)
            except subprocess.TimeoutExpired:
                proc.kill()
            return 130
        except subprocess.TimeoutExpired:
            print("    watchdog expired — killing agy process", flush=True)
            proc.kill()
            proc.wait()
            return 124
    return proc.returncode


# ----------------------------------------------------------------------------- verification

def fresh(path, t0, min_bytes=0):
    return (path.is_file() and path.stat().st_size >= min_bytes
            and path.stat().st_mtime >= t0 - 5)


def verify_iteration(n, t0):
    """All gates must pass: prelecture, lecture, per-lecture PDF, reader deck. Returns failure list."""
    pre = PRE_DIR / f"{bn(n)}.md"
    lec = LEC_DIR / f"{bn(n)}.md"
    pdf = PDF_DIR / f"{bn(n)}.pdf"
    failures = []

    if not (pre.is_file() and pre.stat().st_size >= MIN_PRE_BYTES):
        failures.append(f"prelecture missing/stub: {pre}")
    if not (lec.is_file() and lec.stat().st_size >= MIN_LEC_BYTES):
        failures.append(f"lecture missing/stub: {lec}")
    if not fresh(pdf, t0, MIN_PDF_BYTES):
        failures.append(f"per-lecture PDF missing/stale/too small: {pdf}")
    decks = [Path(p) for p in glob.glob(str(PDF_DIR / DECK_GLOB))]
    if not decks or not any(fresh(d, t0) for d in decks):
        failures.append(f"course-reader deck not regenerated this run (glob: {PDF_DIR / DECK_GLOB})")
    return failures


# ----------------------------------------------------------------------------- main loop

def main():
    ap = argparse.ArgumentParser(
        description="Orchestrate the agy (Antigravity/Gemini) CLI to produce "
                    "react-lecture-03 lectures: one fresh CLI session per question, "
                    "verified end to end before the next one starts.")
    ap.add_argument("chapters", nargs="?", type=int, default=None,
                    help="how many questions/lectures to produce this run (default 1)")
    ap.add_argument("--chapters", dest="chapters_flag", type=int, default=None,
                    help="same as the positional argument")
    ap.add_argument("--start", type=int, default=None,
                    help="first question number (default: auto-detect = max existing lecture + 1)")
    ap.add_argument("--model", default=DEFAULT_MODEL,
                    help=f"agy model slug (default: {DEFAULT_MODEL}; see `agy models`)")
    ap.add_argument("--effort", default=None, choices=["low", "medium", "high"],
                    help="optional reasoning effort flag passed through to agy")
    ap.add_argument("--timeout-min", type=int, default=DEFAULT_TIMEOUT_MIN,
                    help=f"per-iteration agy --print-timeout in minutes (default {DEFAULT_TIMEOUT_MIN})")
    ap.add_argument("--agy", default=DEFAULT_AGY,
                    help=f"path to the Antigravity CLI (default: {DEFAULT_AGY} on PATH)")
    ap.add_argument("--no-preflight", action="store_true",
                    help="skip the `agy models` availability check before each iteration")
    ap.add_argument("--no-skip-permissions", action="store_true",
                    help="do not pass --dangerously-skip-permissions to agy "
                         "(interactive permission prompts will then block print mode)")
    ap.add_argument("--force", action="store_true",
                    help="allow --start to point at a question whose lecture already exists (it gets rewritten)")
    ap.add_argument("--dry-run", action="store_true",
                    help="print the plan, the parsed question row, and the prompt; invoke nothing")
    args = ap.parse_args()

    chapters = args.chapters if args.chapters is not None else args.chapters_flag
    if chapters is None:
        chapters = 1
    if chapters < 1:
        sys.exit("FATAL: --chapters must be >= 1")

    # --- startup sanity
    if not (PROJECT / "src" / "build-lectures.mjs").is_file():
        sys.exit(f"FATAL: not inside the react-lecture-03 project (build script missing at {PROJECT}/src)")
    n = args.start if args.start is not None else detect_next_question()

    print(f"react-lecture-03 agy orchestrator")
    print(f"  project      : {PROJECT}")
    print(f"  model        : {args.model}")
    print(f"  iterations   : {chapters}")
    print(f"  first question: Q{n} (auto-detected)" if args.start is None
          else f"  first question: Q{n} (explicit --start)")

    if n > MAX_QUESTION:
        sys.exit(f"FATAL: next question Q{n} is beyond the 180-question bank — the bank is exhausted.")

    if (LEC_DIR / f"{bn(n)}.md").is_file() and not args.force:
        sys.exit(f"FATAL: md-lectures/{bn(n)}.md already exists. "
                 f"Auto-detect would continue at Q{detect_next_question()}; "
                 f"pass --force to rewrite Q{n} deliberately.")

    row = parse_question_row(n)
    if row is None:
        sys.exit(f"FATAL: question Q{n} not found in {QUESTIONS_MD}")
    prompt = build_prompt(n, row)

    if args.dry_run:
        print("\n=== DRY RUN — nothing will be invoked ===")
        print(f"\nQuestion Q{n}:")
        for k, v in row.items():
            print(f"  {k:8}: {v}")
        print(f"\nagy command: {args.agy} --prompt <see below> --model {args.model}"
              f"{' --effort ' + args.effort if args.effort else ''}"
              f"{' --dangerously-skip-permissions' if not args.no_skip_permissions else ''}"
              f" --print-timeout {args.timeout_min}m  (cwd: {PROJECT})")
        print("\n=== PROMPT ===\n")
        print(prompt)
        print("\n=== END DRY RUN ===")
        return

    LOG_DIR.mkdir(exist_ok=True)
    results = []
    print()

    for i in range(chapters):
        n = args.start if (args.start is not None and i == 0) else n
        stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        log_path = LOG_DIR / f"q{bn(n)}_{stamp}.log"

        print(f"[{i + 1}/{chapters}] Q{n} — tier {row['tier']} — {row['topic']}")
        print(f"    log: {log_path}")

        if not args.no_preflight:
            err = preflight_model(args.agy, args.model)
            if err:
                print(f"    PREFLIGHT FAILED: {err}")
                results.append((n, "preflight-failed", 0, log_path, err))
                break

        t0 = time.time()
        code = run_agy(args.agy, args.model, args.effort, args.timeout_min,
                       not args.no_skip_permissions, prompt, log_path, t0)
        elapsed = time.time() - t0

        if code != 0:
            print(f"    agy exited {code} after {elapsed / 60:.1f} min — stopping (log: {log_path})")
            results.append((n, f"agy-exit-{code}", elapsed, log_path, "see log"))
            break

        failures = verify_iteration(n, t0)
        if failures:
            for f in failures:
                print(f"    VERIFY FAILED: {f}")
            print(f"    Q{n} not verified — stopping. Fix the issue, then rerun; "
                  f"the run resumes at Q{n}. (log: {log_path})")
            results.append((n, "verify-failed", elapsed, log_path, "; ".join(failures)))
            break

        mins = elapsed / 60
        print(f"    VERIFIED: prelecture + lecture + {bn(n)}.pdf + reader deck all present "
              f"({mins:.1f} min)")
        results.append((n, "ok", elapsed, log_path, ""))

        # prepare next iteration
        nxt = n + 1
        if nxt > MAX_QUESTION:
            print(f"    question bank exhausted at Q{MAX_QUESTION}.")
            break
        row = parse_question_row(nxt)
        if row is None:
            print(f"    Q{nxt} not found in the question bank — stopping.")
            break
        prompt = build_prompt(nxt, row)
        n = nxt

    # --- final report
    print("\n" + "=" * 72)
    print("RUN REPORT")
    print("=" * 72)
    ok = sum(1 for r in results if r[1] == "ok")
    for n, status, elapsed, log_path, note in results:
        mark = "DONE" if status == "ok" else "STOP"
        print(f"  Q{n:<4} {mark:5} {status:16} {elapsed / 60:6.1f} min  {Path(log_path).name}"
              + (f"  [{note}]" if note else ""))
    print(f"\n  {ok}/{len(results)} iteration(s) completed successfully"
          + ("" if ok == chapters else f" — run stopped early; rerun to resume from the next question"))
    sys.exit(0 if ok == chapters and ok == len(results) else 1)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\ninterrupted — no partial iteration will be trusted; rerun to resume")
        sys.exit(130)
